include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/main/main_old.dart
    - lib/ms_graph/api/ms_graph_api.chopper.dart
    - '**.g.dart'
    - '**.freezed.dart'
    - '**.chopper.dart'

linter:
  rules:
    public_member_api_docs: false
    no_default_cases: false