name: jambu
description: A new Flutter project.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  chopper: ^7.0.5
  cloud_firestore: ^4.8.5
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.6
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  go_router: ^7.1.1
  intl: 0.17.0
  json_annotation: ^4.8.1
  meta: ^1.9.0
  quiver: ^3.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  video_player: ^2.6.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  chopper_generator: ^7.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/holidays.json
    - assets/images/
    - assets/videos/
