name: jambu
description: A new Flutter project.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.1
  chopper: ^6.1.1
  cloud_firestore: ^4.4.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: 4.2.2
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  go_router: ^6.2.0
  intl: 0.17.0
  json_annotation: ^4.8.0
  meta: ^1.9.0
  quiver: ^3.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/holidays.json
    - assets/images/
