name: jambu
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  firebase_ui_auth: ^1.1.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
