name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0